version: '3.8' 
services:
  django:
    build: .
    container_name: my-django-app
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d